### ISSUE TITLE
Can not find the citation key

### ISSUE THREAD

**Issue by panwanke** [nsalminen/zotero2notion#2]
![image](https://user-images.githubusercontent.com/45927177/142751232-bf0d36c0-36ed-4c7d-b759-62ceed68a91f.png)
How can I get the records citekey?
In your code, it is not function. I am curious how to extract citekey from the "extra" field in your code.
Please help me.

**Comment by Asynchro-Epool** [comment]
I find theCitation key appear in the "extra" field when pinning records citation key. 
https://forums.zotero.org/discussion/82437/betterbibtex-citation-key-when-accessing-group-library-via-server-api-pyzotero/p1

**Comment by nsalminen** [comment]
I'm glad you found it! Let me know if you have any other questions.
